# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Install  dependencies
    init: |
npm install  
    command: npm run install
  - name: Run tests
    init: npm run jest --coverage
    command: test 
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
